meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: postgresql_docker_z1
    templates:
      - name: docker
        release: docker
      - name: postgresql-docker
        release: postgresql-docker
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10

networks: (( merge ))

properties: {}
