---
jobs:
- name: image-pg93
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease}
    - {get: boshrelease-image-pg93, trigger: true}
  - put: docker-image-pg93
    params:
      build: boshrelease/images/postgresql93
- name: image-pg94
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease}
    - {get: boshrelease-image-pg94, trigger: true}
  - put: docker-image-pg94
    params:
      build: boshrelease/images/postgresql94
- name: blobs
  plan:
  - aggregate:
    - {get: docker-image-pg93, passed: [image-pg93]}
    - {get: docker-image-pg94, passed: [image-pg94]}
    - {get: boshrelease}
  - task: update-blobs
    file: boshrelease/ci/tasks/update-blobs.yml

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/postgresql-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}

- name: boshrelease-image-pg93
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/postgresql-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/postgresql93/*]

- name: boshrelease-image-pg94
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/postgresql-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/postgresql94/*]

- name: docker-image-pg93
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql
    tag: 9.3

- name: docker-image-pg94
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql
    tag: 9.4
